M48
; DRILL file {KiCad (6.0.0-0)} date Friday, October 07, 2022 at 06:10:31 pm
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-07T18:10:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X9.5669Y-1.5
X9.5669Y-3.7835
X10.4724Y-1.5
X10.4724Y-3.7835
T0
M30
