M48
; DRILL file {KiCad (6.0.0-0)} date Sunday, October 23, 2022 at 04:11:05 pm
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-23T16:11:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.1772Y-2.6026
X7.3681Y-2.6026
T2
X7.1654Y-2.4833
X7.3799Y-2.4833
T0
M30
