M48
; DRILL file {KiCad (6.0.0-0)} date Thursday, April 14, 2022 at 08:43:55 pm
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-14T20:43:55-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X2.122Y-2.2303
X2.122Y-3.5295
X4.0118Y-2.2303
X4.0118Y-3.5295
T0
M30
